version: 2.1

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test-3-10:
          filters:
            tags:
              only: /.*/

      - test-3-9:
          filters:
            tags:
              only: /.*/

      - test-3-8:
          filters:
            tags:
              only: /.*/

      - test-3-7:
          filters:
            tags:
              only: /.*/

      - image-push:
          filters:
            branches:
              only: /(master|main)/
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/
          requires:
            - test-3-10
            - test-3-9
            - test-3-8
            - test-3-7

      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/
          requires:
            - test-3-10
            - test-3-9
            - test-3-8
            - test-3-7

jobs:
  test-3-10:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - prepare
      - bootstrapping-test
      - unit-test
      - example-test
      - document-build

  test-3-9:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - prepare
      - bootstrapping-test
      - unit-test
      - example-test
      - document-build

  test-3-8:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - prepare
      - bootstrapping-test
      - unit-test
      - example-test
      - document-build

  test-3-7:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - prepare
      - bootstrapping-test
      - unit-test
      - example-test
      - document-build

  image-push:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - docker-image-build-push

  deploy:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - prepare
      - run:
          name: Publish
          command: |
            poetry build
            poetry publish

commands:
  prepare:
    description: Prepare
    steps:
      - run:
          name: Install Poetry
          command: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python

  bootstrapping-test:
    description: Bootstrapping test
    steps:
      - run:
          name: Bootstrapping test
          command: |
            poetry install --no-dev
            poetry run preacher-cli --version
            poetry run preacher-cli --help

  unit-test:
    description: Unit test
    steps:
      - run:
          name: Unit test
          command: |
            poetry install
            poetry run pytest
            poetry run black --check preacher tests examples docs
      - run:
          name: Report
          command: |
            poetry run codecov

  example-test:
    description: Example test
    steps:
      - run:
          name: Example test
          command: |
            poetry install
            poetry run python3 examples/server.py > examples/server.log 2>&1 &
            sleep 5

            # Run normal scenarios.
            poetry run preacher-cli \
              -vv \
              -uhttp://localhost:5000 \
              -Rreport/ \
              ./examples/scenario/success.yml

            # Run plugin scenarios.
            poetry run preacher-cli \
              -vv \
              -uhttp://localhost:5000 \
              -pexamples/plugin/custom_matcher.py \
              ./examples/scenario/plugin.yml

            # Run plugin scenarios with installation.
            poetry run pip install ./examples/plugin
            poetry run preacher-cli \
              -vv \
              -uhttp://localhost:5000 \
              ./examples/scenario/plugin.yml

            ls report/
            cat examples/server.log

  document-build:
    description: Build documents
    steps:
      - run:
          name: Build documents
          command: |
            poetry install
            poetry run make html

  docker-image-build-push:
    description: Build the Docker image and push it
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Install aws-cli to push the image into ECR
          command: |
            pip install awscli==1.24.9
      - run:
          name: Install Docker Buildx
          command: |
            mkdir -p ~/.docker/cli-plugins/
            curl -sL "https://github.com/docker/buildx/releases/download/v0.8.0/buildx-v0.8.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            sudo apt-get update && sudo apt-get install -y binfmt-support qemu-user-static
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker run --privileged --rm tonistiigi/binfmt --install arm64
            docker context create buildcontext
            docker buildx create buildcontext --use
      - run:
          name: Build Docker images
          no_output_timeout: 30m
          command: |
            docker buildx build --load --progress plain --platform linux/arm64/v8 -t preacher:arm64-v8 .
            docker build --platform linux/amd64 -t preacher:amd64 .
      - run:
          name: Push Docker images
          command: |
            function push() {
              local image="${1:?}"

              local image_amd64_v8="${image}-arm64-v8"
              docker tag preacher:arm64-v8 "${image_amd64_v8}"
              docker push "${image_amd64_v8}"

              local image_amd64="${image}-amd64"
              docker tag preacher:amd64 "${image_amd64}"
              docker push "${image_amd64}"

              docker manifest create "${image}" "${image_amd64_v8}" "${image_amd64}"
              docker manifest push "${image}"
            }

            IMAGE_TAG=latest
            if [[ -n "${CIRCLE_TAG}" ]]; then
              IMAGE_TAG="${CIRCLE_TAG}"
            fi
            echo "Image Tag: ${IMAGE_TAG}"

            echo "${DOCKER_HUB_PASSWORD}" | docker login --username "${DOCKER_HUB_USERNAME}" --password-stdin
            push "ymoch/preacher:${IMAGE_TAG}"

            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/ymoch
            push "public.ecr.aws/ymoch/preacher:${IMAGE_TAG}"
